"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6qp55sc#z!5a*!f@112))c$msar6u)i8lq-cj843d*gt^$4b5l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'shop_app',

    # Allauth applar
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Google provider
]

SITE_ID = 1

# Autentifikatsiya backendlarini sozlash
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Login bo'lgandan keyin qaysi sahifaga o'tishi kerak
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Allauth sozlamalari
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# Google Provider sozlamalari
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR/'static']
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR/'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'shop_app.CustomUser'

# settings.py

JAZZMIN_SETTINGS = {
    # Sayt nomlari
    "site_title": "Creative Admin",  # Brauzer tabida ko'rinadigan nom
    "site_header": "Creative Hub",   # Login va admin tepasidagi katta sarlavha
    "site_brand": "CreativeOS",      # Sidebar tepasidagi brend nomi (qisqa bo'lsin)
    "welcome_sign": "Ijodiy boshqaruv paneliga xush kelibsiz!",
    "copyright": "Creative Hub MChJ",

    # Logotip sozlamalari (static papkangizga logotip rasmini joylang)
    "site_logo": "img/creative-logo.svg",  # Yorqin fon uchun
    "login_logo": "img/creative-logo-dark.svg", # Agar dark theme bo'lsa
    "site_logo_classes": "elevation-2",  # Logotipga soya berish
    "site_icon": "img/favicon.ico",     # Brauzer ikonkasi

    # Interfeys sozlamalari
    "show_sidebar": True,
    "navigation_expanded": False,  # Menyular yig'ilgan holda chiroyli ko'rinadi
    "show_ui_builder": True,       # O'ng tepadagi UI sozlagich tugmasi

    # Tepadagi menyu linklari
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Saytga o'tish", "url": "/", "new_window": True, "icon": "fas fa-external-link-alt"},
        {"app": "myapp"},  # "myapp" o'rniga o'zingizning asosiy app nomini yozing
    ],

    # Sidebar uchun kreativ ikonkalar (Font Awesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-astronaut",      # Kreativroq ikonka
        "auth.group": "fas fa-layer-group",
        # O'zingizning modellaringiz uchun:
        # "myapp.MyModel": "fas fa-cube",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-thumbs-up",  # Default nuqta o'rniga

    # Modallar va formalar
    "related_modal_active": True,  # Pop-up o'rniga chiroyli modal oynalar
    "changeform_format": "vertical_tabs",  # Vertikal tablar zamonaviy ko'rinadi
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # Asosiy tayyor tema
    "dark_mode_theme": "darkly",  # Tungi rejim uchun tema
    "navbar": "navbar-white navbar-light",  # Oq navbar
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-warning",  # Yon panel fon rangi
    "sidebar_nav_flat_style": False,
    "sidebar_nav_child_indent": False,
    "sidebar_disable_expand": False,
    "brand_colour": "navbar-teal",  # Brend qismi uchun rang (teal)
    "brand_small_text": False,
    "accent": "accent-teal",        # Tugma va linklar aksent rangi
    "button_rounded": True,         # Dumaloq burchakli tugmalar
    "body_small_text": False,
    "navbar_small_text": False,
    "footer_small_text": True,
    "actions_sticky_bottom": True,  # Pastki "Saqlash" paneli yopishib qoladi
}